# Generated by Django 3.2.9 on 2021-11-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='patient_id',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
